[project]
name = "openintel"
version = "0.1.0"
description = "A small Competitive Intelligence Engine for SaaS/Web Apps"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "playwright>=1.54.0",
]
